variables:
  CI_DOCKERHUB_REGISTRY_IMAGE: "martadinata666/beatbump" 
  npm_config_cache: "$CI_PROJECT_DIR/.npm-cache"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"
  GITHUB_REPO_NAME: "snuffyDev/Beatbump"

stages:
  - build-js
  - dockerized

build-js:
  image: 192.168.0.2:5050/dedyms/node:lts-dev
  stage: build-js
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store/
      - .npm-cache/
      - .yarn-cache/
    policy: pull-push
  before_script:
    - pnpm config set store-dir $CI_PROJECT_DIR/.pnpm-store
    - export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
    - export NODE_ENV=development
    - apt update && apt install -y --no-install-recommends git jq curl
    #- export RELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_REPO_NAME/releases/latest" | jq -r .tag_name)
    #- echo $RELEASE
    - git clone --depth=1 -b rewrite https://github.com/snuffyDev/Beatbump.git beatbump
  script:
    - cd beatbump
    - npm ci
    - npm run build
  artifacts:
    paths:
      - beatbump/build
  only:
    changes:
      - Dockerfile

buildx-docker:
  cache: []
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: dockerized
  before_script:
    - export RELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_REPO_NAME/releases/latest" | jq -r .tag_name)
    - export RELEASE="git"
    #- echo $RELEASE    
    #- export DATE=$(date +%Y%m%d)
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64,linux/amd64 --build-arg RELEASE=$RELEASE -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" . -f Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm
  only:
    changes:
      - Dockerfile

