jobs:
  - name: self
    command: echo "I'm Up"
    shell: /bin/bash
    schedule: "*/5 * * * *"
  # Some additional jobs, not including this line
  #- name: nextcloud-preview-generate
  #  command: php -f /var/www/html/occ -vvv preview:pre-generate
  #  schedule: "*/30 * * * *"
  #  utc: false
  #  #executionTimeout: 120

logging:
  # In the format of:
  # https://docs.python.org/3/library/logging.config.html#dictionary-schema-details
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s %(levelname)s [%(name)s]: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers:
      - console
