#syntax=docker/dockerfile:1.4
FROM rust:slim-bullseye
RUN apt update && \
    apt install -y --no-install-recommends curl git wget libssl-dev build-essential make perl && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt update && \
    apt install -y --no-install-recommends nodejs && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    npm install -g npm && \
    npm install -g yarn && \
    npm install -g pnpm && \
    rm -rf $HOME/.config
RUN cargo install wasm-pack && \
    npm install -g rollup
CMD ["bash"]
