stages:
  - composer
  - build-ui
  - dockerize

variables:
  CI_DOCKERHUB_REGISTRY_IMAGE: "index.docker.io/martadinata666/afterlogic-webmail"
  TYPE: ""
  GITHUB_REPO_NAME: "afterlogic/webmail-lite-8"
  PLATFORM: linux/arm64,linux/amd64
  npm_config_cache: "$CI_PROJECT_DIR/.npm-cache"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"

#fetch-composer-depths:
#  image: 192.168.0.2:5050/dedyms/php-fpm:8
#  stage: composer
  
  
#build-themes-admin-ui:
#  image: 192.168.0.2:5050/dedyms/node:lts-dev
#  stage: build-ui
#  cache:
#    key: "$CI_COMMIT_REF_SLUG"
#    paths:
#      - .pnpm-store/
#      - .npm-cache/
#      - .yarn-cache/
#      - vendor/
#    policy: pull-push
#  before_script:
#    - pnpm config set store-dir .pnpm-store
#    - npm config set fetch-retries 100
#    - npm config set fetch-retry-mintimeout 99999999
#    - npm config set fetch-retry-maxtimeout 99999999 
#    - git clone --depth=1 https://github.com/afterlogic/webmail-lite-8.git web
#  script:
#    - cd web
#    - npm -d install
#    - npm -d install -g gulp-cli @quasar/cli
#    - cd web/modules/AdminPanelWebclient/vue
#    - npm -d install
#    - cd ../../../
#    - gulp styles --themes Default,DeepForest,Funny,Sand
#    - gulp js:min
#    - cd web/modules/AdminPanelWebclient/vue
#    - npm -d run build-production
#    - cd ../../../
#    - rm -rf web/system/.git
#    - rm -rf web/node_modules/
#    - rm -rf web/modules/AdminPanelWebclient/vue/node_modules
#  artifacts:
#    paths:
#      - web/
#  only:
#    refs:
#      - master

create-docker-image:
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: dockerize
  before_script:
    - export RELEASE="git"
    - export DATE=$(date +%Y%m%d)
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/amd64,linux/arm64  -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_REGISTRY_IMAGE:$DATE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$DATE" . -f Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm
  only:
    refs:
      - master
