FROM 192.168.0.2:5050/dedyms/debian:latest as cleaner
COPY web /web
WORKDIR /web
RUN rm -rf system/.git

FROM 192.168.0.2:5050/dedyms/apache:fpm
COPY --from=cleaner --chown=$CONTAINERUSER:$CONTAINERUSER web /var/www/html
USER $CONTAINERUSER
VOLUME ["/var/www/html/data"]
