jobs:
  - name: self
    command: echo "I'm Up"
    shell: /bin/bash
    schedule: "*/5 * * * *"
  # Some additional jobs, not including this line
  #- name: nextcloud-preview-generate
  #  command: php -f /var/www/html/occ -vvv preview:pre-generate
  #  schedule: "*/30 * * * *"
  #  utc: false
  #  #executionTimeout: 120
