#syntax=docker/dockerfile:1.4
FROM rust:slim-bullseye
RUN apt update && \
    apt install -y --no-install-recommends ca-certificates git && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
CMD ["bash"]

# ca-certificates libva-dev sqlite libdrm-dev curl git build-base