# This file is a template, and might need editing before it works on your project.
variables:
  #LIBTORRENT: ""
  #QBIT: ""
  CI_DOCKERHUB_REGISTRY_IMAGE: "index.docker.io/martadinata666/qbittorrent-nox"
  GITHUB_REPO_NAME: "userdocs/qbittorrent-nox-static"
  GITHUB_MATUI_REPO_NAME: "bill-ahmed/qbit-matui"

buildx-stable:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
  before_script:
    #- apk add curl jq
    - export RELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_REPO_NAME/releases/latest" | jq -r .tag_name)
    - export RELEASE1=$(curl --silent "https://api.github.com/repos/$GITHUB_REPO_NAME/releases" | jq -r 'first(.[] | select(.tag_name | contains("1.2"))) | .tag_name')
    - echo $RELEASE
    - echo $RELEASE1
    - export MATUIRELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_MATUI_REPO_NAME/releases/latest" | jq -r .tag_name)
    - echo $MATUIRELEASE
    - export ZIPRELEASE=$(echo $MATUIRELEASE | cut -c 2-)
    - echo $ZIPRELEASE
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml --driver-opt image=moby/buildkit:"$BUILDKIT_VERSION"
    - docker buildx inspect --bootstrap
    - docker buildx build --build-arg QBVERSION=$RELEASE --build-arg MATUIRELEASE=$MATUIRELEASE --build-arg ZIPRELEASE=$ZIPRELEASE --push --platform linux/arm64,linux/amd64
      -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE"  . -f Dockerfile
    - docker buildx build --build-arg QBVERSION=$RELEASE1 --build-arg MATUIRELEASE=$MATUIRELEASE --build-arg ZIPRELEASE=$ZIPRELEASE --push --platform linux/arm64,linux/amd64
      -t "$CI_REGISTRY_IMAGE:libtorrent1" -t "$CI_REGISTRY_IMAGE:$RELEASE1" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:libtorrent1" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE1"  . -f Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm
  only:
    refs:
      - master
      - schedules
    changes:
      - Dockerfile
