[LegalNotice]
Accepted=true

[Preferences]
Downloads\SavePath=/home/debian/qbittorrent/downloads/
Downloads\TempPath=/home/debian/qbittorrent/downloads/incomplete/
WebUI\AlternativeUIEnabled=true
WebUI\RootFolder=/home/debian/qbittorrent/VueTorrent

