# This file is a template, and might need editing before it works on your project.
variables:
  RELEASE: ""
  SCHEDULE_TYPE: ""
  DATE: ""
  DOCKERHOST: tcp://docker:2375
  #DOCKER_DRIVER: overlay2

docker-buildx-base-image:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:0.5.1
  stage: build
  services:
    - docker:dind
  before_script:
    - export DATE=$(date +%Y%m%d)
    - export RELEASE=weekly
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:$DATE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$DATE" -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" -t "$CI_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" .
  except:
    - schedules
  only:
    #variables:
    #  - $SCHEDULE_TYPE == "weekly"
    refs:
      - master
      - schedules
    changes:
      - Dockerfile
