# This file is a template, and might need editing before it works on your project.
variables:
  DISTRO: ""
  CI_DOCKERHUB_REGISTRY_IMAGE: "index.docker.io/martadinata666/docker-binfmt-qemu"

buildx:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
  before_script:
    - export RELEASE_STATIC="sid"
#    - export RELEASE=$(grep -m1 QEMU_VERSION Dockerfile | cut -c18-)
#    - echo $RELEASE
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml --name $CI_PROJECT_NAME --driver-opt image=moby/buildkit:"$BUILDKIT_VERSION"
#    - docker buildx create --config buildx-config.toml --append "$DOCKER_ARM_HOST" --name buildx-qemu-static --platform linux/arm64
    - docker buildx inspect --bootstrap
#    - docker buildx build --push --platform linux/amd64,linux/arm64 -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$RELEASE" . -f Dockerfile
    - docker buildx build . --push --platform linux/amd64
      -t "$CI_REGISTRY_IMAGE"
      -t "$CI_REGISTRY_IMAGE:$RELEASE_STATIC"
      -f Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm -f
  only:
    refs:
      - master
    changes:
      - Dockerfile

#build-buster:
#  # Official docker image.
#  image: docker:latest
#  stage: build
#  services:
#    - docker:dind
#  before_script:
#    - export DISTRO="buster"
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:$DISTRO" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$DISTRO" . -f Dockerfile.$DISTRO
#    - docker push "$CI_REGISTRY_IMAGE:$DISTRO"
#    - docker push "$CI_DOCKERHUB_REGISTRY_IMAGE:$DISTRO"
#  only:
#    refs:
#      - master
#    changes:
#      - Dockerfile.buster
