#syntax=docker/dockerfile:1.4
FROM debian:buster-slim

RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends binfmt-support qemu-user-static \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["sh", "-c", "update-binfmts --enable && dpkg-reconfigure qemu-user-static"]
