#syntax=docker/dockerfile:1.4
FROM debian:sid-slim
RUN echo 'deb http://deb.debian.org/debian experimental main' > /etc/apt/sources.list.d/experimental.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends -t experimental binfmt-support qemu-user-static && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["sh", "-c", "update-binfmts --enable && dpkg-reconfigure qemu-user-static"]
