jobs:
  - name: background-update
    command: bash -c 'curl -sS -L https://picsum.photos/1920/1080.webp -o /var/www/html/public/img/bg1.webp'
    shell: /bin/bash
    schedule: "0 * * * *"
#    failsWhen:
#      producesStdout: false
#      producesStderr: false
  # Some additional jobs, not including this line
  #- name: nextcloud-preview-generate
  #  command: php -f /var/www/html/occ -vvv preview:pre-generate
  #  schedule: "*/30 * * * *"
  #  utc: false
  #  #executionTimeout: 120
