FROM rust:slim-bullseye
RUN apt update && \
    apt install -y ca-certificates libva2 libva-dev sqlite3 libdrm2 \
                   libdrm-dev libdrm-amdgpu1 curl \
                   build-essential pkg-config libssl-dev && \
   apt clean && \
   rm -rf /var/lib/apt/lists/*
CMD ["bash"]

# ca-certificates libva-dev sqlite libdrm-dev curl git build-base