name: PyInstaller Test Debian

# Need manually created
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
# DOCKERHUB_IMAGE_NAME

on:
  push:
    branches: [ 'dockerfile-debian' ] #rolling build on develop only
    tags: 'v*' #tag for specific release v1.0.2,or anytag, start with v
  pull_request:
    branches: [ 'main' ] #build test on main, not pushing
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.9","3.10","3.11"]
    container:
      image: python:${{ matrix.version  }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install deps
        run: |
             apt update
             apt install -y curl git ca-certificates build-essential zlib1g-dev libbz2-dev libssl-dev libreadline-dev libffi-dev upx-ucl
      - name: Fetch pyinstaller deps
        run: |
             git config --global --add safe.directory /__w/yacron/yacron
             git status
             python3 setup.py install
             pip3 install pyinstaller
             python3 pyinstaller/yacron --version
             pyinstaller pyinstaller/yacron.spec
             ls -sFh dist/yacron
             dist/yacron --version



#             pip3 install -r pyinstaller/requirements310.txt