variables:
  RELEASE: ""

#docker-buildx-git:
  # Official docker image.
#  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
#  stage: build
#  services:
#    - docker:dind
#  before_script:
#    - export  RELEASE="git"
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
#    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:buster
#  script:
#    - docker buildx create --use
#    - docker buildx inspect --bootstrap
#    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" -t "$CI_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" .
#  only:
#    variables:
#      - $RELEASE == "git"
#    refs:
#      - master
#      - schedules

#docker-buildx-discord:
#  # Official docker image.
#  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
#  stage: build
#  services:
#    - docker:dind
#  before_script:
#    - export RELEASE="discord"#
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
#    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:buster
#  script:
#    - docker buildx create --use
#    - docker buildx inspect --bootstrap
#    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE"  . -f Dockerfile.discord
#  only:
#    variables:
#      - $RELEASE == "discord"
#    refs:
#      - master
#      - schedules


#docker-buildx-test:
#  # Official docker image.
#  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
#  stage: build
#  services:
#    - docker:dind
#  before_script:
#    - export RELEASE=$CI_COMMIT_SHORT_SHA
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
#    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:buster
#  script:
#    - docker buildx create --use
#    - docker buildx inspect --bootstrap
#    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" . -f Dockerfile.discord
#  only:
#    refs:
#      - master
#      - schedules
#    changes:
      #- Dockerfile
      #- Dockerfile.discord
      #- shepherd
      #- shepherd.discord
      #- .gitlab-ci.yml

docker-buildx-cronjob:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
  before_script:
    - export RELEASE="cronjob"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #- docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml --driver-opt image=moby/buildkit:"$BUILDKIT_VERSION"
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform "$BUILD_PLATFORM" -t "$CI_REGISTRY_IMAGE:$RELEASE" . -f Dockerfile.cronjob
  only:
    #variables:
    #  - $RELEASE == "cronjob"
    refs:
      - master
      - schedules
    changes:
      - Dockerfile.cronjob
      - shepherd.cronjob.update
