version: "3.6"
services:
  pihole_exporter:
    image: pihole-exporter:local
    expose:
      - 9617
    environment:
      - PIHOLE_HOSTNAME=192.168.0.11
      - PIHOLE_PORT=80
      - PIHOLE_PASSWORD=nr6s3p
      - INTERVAL=30s
      - PORT=9617
    restart: always