variables:
  CI_DOCKERHUB_REGISTRY_IMAGE: "index.docker.io/martadinata666/jre"

buildx-jre:
  cache: {}
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
  before_script:
    - export DATE=$(date +%Y%m%d)
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:11" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:11" . -f Dockerfile.jre11
  after_script:
    - docker buildx stop
    - docker buildx -f
  #except:
  #  - schedules
  only:
    - triggers
