FROM 192.168.0.2:5050/dedyms/debian:latest
RUN mkdir -p /usr/share/man/man1 && apt update && apt install -y --no-install-recommends openjdk-11-jre-headless && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
