FROM 192.168.0.2:5050/dedyms/debian:latest
RUN sudo mkdir -p /usr/share/man/man1 && \
    sudo apt update && \
    sudo apt install -y --no-install-recommends openjdk-11-jre-headless && \
    sudo apt clean && \
    sudo rm -rf /var/lib/apt/lists/*
USER $CONTAINERUSER
CMD ["/bin/bash"]
