# This file is a template, and might need editing before it works on your project.
variables:
  DATE: ""
  VERSION: ""
  CI_DOCKERHUB_REGISTRY_IMAGE: "martadinata666/ffmpeg-static"

buildx-static:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64,linux/amd64 --build-arg VERSION=$VERSION -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$VERSION" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$VERSION" . -f Dockerfile
  only:
    - triggers
