variables:
  CI_DOCKERHUB_REGISTRY_IMAGE: "index.docker.io/martadinata666/novnc-desktop"
  GITHUB_REPO_NAME: "novnc/noVNC"

buildx-xfce4:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
  before_script:
#    - export RELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_REPO_NAME/releases/latest" | jq -r .tag_name)
    - export RELEASE="xfce4"
    - echo $RELEASE
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
#    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
#    - docker buildx create --use --config buildx-config.toml
    - docker buildx create --use --config buildx-config.toml --name buildx-novnc-desktop --platform linux/amd64
    - docker buildx create --config buildx-config.toml --append "$DOCKER_ARM_HOST" --name buildx-novnc-desktop --platform linux/arm64
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" . -f xfce4/Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm -f
  only:
    refs:
      - master
      - schedules
    changes:
      - xfce4/Dockerfile

buildx-openbox:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
  before_script:
#    - export RELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_REPO_NAME/releases/latest" | jq -r .tag_name)
    - export RELEASE="openbox"
    - echo $RELEASE
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
#    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
#    - docker buildx create --use --config buildx-config.toml
    - docker buildx create --use --config buildx-config.toml --name buildx-novnc-desktop --platform linux/amd64
    - docker buildx create --config buildx-config.toml --append "$DOCKER_ARM_HOST" --name buildx-novnc-desktop --platform linux/arm64
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" . -f openbox/Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm -f
  only:
    refs:
      - master
      - schedules
    changes:
      - openbox/Dockerfile
