# This file is a template, and might need editing before it works on your project.
variables:
  RELEASE: ""
  CI_DOCKERHUB_REGISTRY_IMAGE: "martadinata666/iperf3"
#  BUILDKIT_UNSAFE_HTTP: 1
#  DOCKER_HOST: tcp://docker:2375

buildx-stable:
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
#  services:
#    - name: docker:dind
  before_script:
    - export RELEASE="sid"
    #- docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:test
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
#    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:latest
  script:
#    - docker buildx create --use --config buildkit-config.toml --driver-opt image=moby/buildkit:v0.14.0
    - docker buildx create --use --config buildkit-config.toml
    - docker info
    - docker buildx version
#    - docker buildx create --use --config ./buildkit-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform "$BUILD_PLATFORM" -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$RELEASE" . -f Dockerfile
#    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" . -f Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm -f
  only:
    refs:
      - master
      - schedules
    changes:
      - Dockerfile
