# This file is a template, and might need editing before it works on your project.
variables:
  MAIN: "main"
  WORKER: "worker"
  RELEASE: "v2.0.1"
docker-build-papermerge:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
  script:
    - docker build --build-arg BRANCH=$RELEASE --pull -t "$CI_REGISTRY_IMAGE:$MAIN$RELEASE" -t "$CI_REGISTRY_IMAGE:$MAIN" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$MAIN$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$MAIN" . -f app.dockerfile
    - docker push "$CI_REGISTRY_IMAGE:$MAIN"
    - docker push "$CI_REGISTRY_IMAGE:$MAIN$RELEASE"
    - docker push "$CI_DOCKERHUB_REGISTRY_IMAGE:$MAIN"
    - docker push "$CI_DOCKERHUB_REGISTRY_IMAGE:$MAIN$RELEASE"
  only:
    refs:
      - master
    changes:
      - app.dockerfile
      - .gitlab-ci.yml

docker-build-papermerge-worker:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --build-arg BRANCH=$RELEASE --pull -t "$CI_REGISTRY_IMAGE:$WORKER$RELEASE" -t "$CI_REGISTRY_IMAGE:$WORKER" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$WORKER$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$WORKER" . -f worker.dockerfile
    - docker push "$CI_REGISTRY_IMAGE:$WORKER"
    - docker push "$CI_REGISTRY_IMAGE:$WORKER$RELEASE"
    - docker push "$CI_DOCKERHUB_REGISTRY_IMAGE:$WORKER"
    - docker push "$CI_DOCKERHUB_REGISTRY_IMAGE:$WORKER$RELEASE"
  only:
    refs:
      - master
    changes:
      - worker.dockerfile
      - .gitlab-ci.yml
