FROM 192.168.0.2:5050/dedyms/nginx:mainline
COPY --chown=$CONTAINERUSER:$CONTAINERUSER jellyfin-vue/frontend/dist/ /var/www/html
COPY --chown=$CONTAINERUSER:$CONTAINERUSER static/nginx.conf /etc/nginx/conf.d/default.conf
