# This file is a template, and might need editing before it works on your project.
variables:
  RELEASE: ""
  UPDATE: ""
  DATE: ""
  CI_DOCKERHUB_REGISTRY_IMAGE: "index.docker.io/martadinata666/debian"
  GITHUB_REPO_NAME: "jellyfin/jellyfin-ffmpeg"

stages:
  - build-base
  - build-base-dev
  - build-vaapi

buildx-baseimage:
  cache: {}
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build-base
  before_script:
    - export DATE=$(date +%Y%m%d)
    #- apk add --no-cache curl
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    #- docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:buster" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:buster" . -f buster/Dockerfile
    #- docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:bullseye" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:bullseye" . -f bullseye/Dockerfile
    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:sid" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:sid" -t "$CI_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" . -f sid/Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm
  except:
    - schedules
  only:
    - triggers

buildx-base-dev:
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build-base-dev
  before_script:
    - export DATE=$(date +%Y%m%d)
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #- docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64,linux/amd64 -t "$CI_REGISTRY_IMAGE:dev" . -f bullseye/Dockerfile.dev
  after_script:
    - docker buildx stop
    - docker buildx rm
    - echo "Trigger NODE image rebuild"
    - curl -X POST --fail -F token=$NODE_TOKEN -F ref=master http://192.168.0.2:10000/api/v4/projects/37/trigger/pipeline
    #- echo "Trigger jre image rebuild"
    #- curl -X POST --fail -F token=$JRE_TOKEN -F ref=master http://192.168.0.2:10000/api/v4/projects/38/trigger/pipeline
    - echo "Trigger APACHE image rebuild"
    - curl -X POST --fail -F token=$APACHE_TOKEN -F ref=master http://192.168.0.2:10000/api/v4/projects/39/trigger/pipeline
    - echo "Trigger NGINX image rebuild"
    - curl -X POST --fail -F token=$NGINX_TOKEN -F ref=master http://192.168.0.2:10000/api/v4/projects/40/trigger/pipeline
    - echo "Trigger PING build"
    - curl -X POST --fail -F token=$PING_TOKEN -F ref=master http://192.168.0.2:10000/api/v4/projects/90/trigger/pipeline
    - echo "Trigger IPERF3 build"
    - curl -X POST --fail -F token=$IPERF3_TOKEN -F ref=master http://192.168.0.2:10000/api/v4/projects/42/trigger/pipeline
  only:
    - triggers

buildx-vaapi:
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build-vaapi
  before_script:
    - export DATE=$(date +%Y%m%d)
    - export RELEASE=$(grep -m1 "NEO_VERSION" bullseye/Dockerfile.vaapi | cut -c17-)
    - echo $RELEASE
    - export JELLYFIN_RELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_REPO_NAME/releases/latest" | jq -r .tag_name | cut -c2-)
    - echo $JELLYFIN_RELEASE
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/arm64,linux/amd64 --build-arg JELLYFIN_VERSION=$JELLYFIN_RELEASE -t "$CI_REGISTRY_IMAGE:vaapi" -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:vaapi" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" . -f bullseye/Dockerfile.vaapi
  after_script:
    - docker buildx stop
    - docker buildx rm
  only:
    refs:
      - master
    changes:
      - bullseye/Dockerfile.vaapi
