FROM 192.168.0.2:5050/dedyms/debian:bullseye
# https://github.com/intel/compute-runtime/releases
ARG TARGETARCH
#ARG GMMLIB_VERSION=22.0.2
#ARG IGC_VERSION=1.0.10395
#ARG NEO_VERSION=22.08.22549
#ARG LEVEL_ZERO_VERSION=1.3.22549
# If needed downgrade jellyfin-ffmpeg
# https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-bullseye_amd64.deb

RUN groupadd -g 139 render && \
    gpasswd -a $CONTAINERUSER render && \
    gpasswd -a $CONTAINERUSER video

# Intel VAAPI Tone mapping dependencies:
# Prefer NEO to Beignet since the latter one doesn't support Comet Lake or newer for now.
# Do not use the intel-opencl-icd package from repo since they will not build with RELEASE_WITH_REGKEYS enabled.
RUN if [ "${TARGETARCH}" = "amd64" ]; then \
        echo 'deb http://deb.debian.org/debian bullseye non-free' > /etc/apt/sources.list.d/experimental.list && \
        apt update && apt install -y --no-install-recommends wget && \
        mkdir intel-compute-runtime && \
        cd intel-compute-runtime && \
        wget https://github.com/intel/compute-runtime/releases/download/22.05.22297/intel-gmmlib_22.0.0_amd64.deb && \
        wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9933/intel-igc-core_1.0.9933_amd64.deb && \
        wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.9933/intel-igc-opencl_1.0.9933_amd64.deb && \
        wget https://github.com/intel/compute-runtime/releases/download/22.05.22297/intel-opencl-icd_22.05.22297_amd64.deb && \
        wget https://github.com/intel/compute-runtime/releases/download/22.05.22297/intel-level-zero-gpu_1.3.22297_amd64.deb && \
        dpkg -i *.deb && \
        cd .. && \
        rm -rf intel-compute-runtime; \
    fi;


# echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list && \
RUN apt update && apt install --no-install-recommends -y ca-certificates gnupg wget apt-transport-https \
    && wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | apt-key add - \
    && echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/debian bullseye main" | tee /etc/apt/sources.list.d/jellyfin.list \
    && apt-get update \
    && apt install --no-install-recommends --no-install-suggests -y mesa-va-drivers jellyfin-ffmpeg \
    && ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg \
    && ln -s /usr/lib/jellyfin-ffmpeg/ffprobe /usr/local/bin/ffprobe \
    && apt-get remove gnupg apt-transport-https -y \
    && apt-get clean autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
