#syntax=docker/dockerfile:1.4
FROM 192.168.0.2:5050/dedyms/debian:latest 

RUN apt update && \
    apt install -y --no-install-recommends build-essential git autotools-dev autoconf automake libtool gettext gawk \
                                           python3-pip python3-dev libcurl4-gnutls-dev libgnutls28-dev libvips-dev python3-setuptools grc \
                                           wget unzip python3-dev ca-certificates libva2 libva-dev sqlite3 libdrm2 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*