#syntax=docker/dockerfile:1.4
FROM 192.168.0.2:5050/dedyms/nginx:mainline-fpm
# Switch to root, to install xdebug
USER root
RUN apt update && apt install -y --no-install-recommends $PHPIZE_DEPS && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    apt remove -y --purge $PHPIZE_DEPS && \
    apt autoremove -y --purge && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
USER $CONTAINERUSER
