jobs:
  - name: nextcloud-cron
    command: php -f /var/www/html/cron.php
    schedule: "*/5 * * * *"
    utc: false
    executionTimeout: 120

jobs:
  - name: nextcloud-preview-generate
    command: /var/www/html/occ preview:pre-generate -vvv
    schedule: "*/30 * * * *"
    utc: false
    #executionTimeout: 120
