#syntax=docker/dockerfile:1.4
FROM 192.168.0.2:5050/dedyms/node:lts-dev as builder
RUN apt update && apt install -y --no-install-recommends libvips-dev libtool && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
