 # Builder
FROM 192.168.0.2:5050/dedyms/cadvisor:dev as builder
ARG VERSION=$VERSION
ENV CADVISOR_VERSION=$VERSION
RUN apt update && apt install -y --no-install-recommends git dmsetup
RUN git clone --depth=1 --branch ${CADVISOR_VERSION} https://github.com/martadinata666/cadvisor.git /go/src/github.com/google/cadvisor
WORKDIR /go/src/github.com/google/cadvisor
ENV GOARCH=arm
RUN make build
 
# Image for usage
FROM debian:bullseye-slim
COPY --from=builder /go/src/github.com/google/cadvisor/cadvisor /usr/bin/cadvisor
ENTRYPOINT ["/usr/bin/cadvisor","-logtostderr","-docker_only"]
