#syntax=docker/dockerfile:1.4
# Builder
FROM 192.168.0.2:5050/dedyms/cadvisor:dev as builder
ARG VERSION=$VERSION
ENV CADVISOR_VERSION=$VERSION
#RUN git clone --depth=1 --branch release-v0.43 https://github.com/google/cadvisor.git /go/src/github.com/google/cadvisor
RUN git clone --depth=1 --branch master --depth=1 https://github.com/google/cadvisor.git /go/src/github.com/google/cadvisor
WORKDIR /go/src/github.com/google/cadvisor
RUN case ${TARGETPLATFORM} in \
         "linux/amd64")  GO_FLAGS="-tags=libipmctl,libfpm,netgo"  ;; \
    esac \ 
    && make build
#RUN make build

# Image for usage
FROM 192.168.0.2:5050/dedyms/debian:latest
ENV CADVISOR_VERSION=master
#RUN apt update && apt install --no-install-recommends tini && apt clean && rm -rf /var/lib/apt/lists/*
RUN if [ "${TARGETARCH}" = "amd64" ]; then \
        apt update && \
        apt install -y --no-install-recommends libpfm4 libipmctl4 wget && \
        apt clean && \
        rm -rf /var/lib/apt/lists/*; \
    fi;
COPY --from=builder /go/src/github.com/google/cadvisor/cadvisor /usr/bin/cadvisor
HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --quiet --tries=1 --spider http://localhost:8080/healthz || exit 1
ENTRYPOINT ["/usr/bin/tini","-g","--","/usr/bin/cadvisor","-logtostderr"]
