#syntax=docker/dockerfile:1.4
FROM 192.168.0.2:5050/dedyms/debian:latest
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
    apt update && apt install -y --no-install-recommends nodejs && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    npm install -g yarn && \
    npm install -g pnpm && \
    rm -rf $HOME/.config
CMD ["/bin/bash"]
