
FROM 192.168.0.2:5050/dedyms/node:14-buster
RUN apt update && apt install -y --no-install-recommends zip unzip git wget build-essential && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
