#syntax=docker/dockerfile:1.4
FROM 192.168.0.2:5050/dedyms/debian:dev
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt update && apt install -y --no-install-recommends nodejs zip unzip git wget build-essential && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    npm install -g npm && \
    npm install -g yarn && \
    npm install -g pnpm && \
    ln -s /usr/bin/eatmydata /usr/local/bin/node && \
    rm -rf $HOME/.config
CMD ["/bin/bash"]
