server {
  listen 80 default_server;
  
  root /var/www/html/public;
  set $htpasswd_file /var/www/html/public/.htpasswd;
  set $auth_basic "Restricted";
  if (!-f $htpasswd_file) {
    set $auth_basic off;
  }

  location / {
    auth_basic $auth_basic;
    auth_basic_user_file $htpasswd_file;
    try_files $uri /index.php$is_args$args;
  }
  
  location ~ ^/index\.php(/|$) {
    fastcgi_pass fpm:9000;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include fastcgi_params;
    fastcgi_param HTTP_PROXY "";
    fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
  }
  
  location ~ \.php$ {
    return 404;
  }
}
