FROM registry.gitlab.com/dedyms/pixapop:cache AS cache

FROM registry.gitlab.com/dedyms/nginx:mainline
COPY --chown=$CONTAINERUSER:$CONTAINERUSER --from=cache /home/fpm/pixapop/ /var/www/html/
COPY default.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www/html
USER $CONTAINERUSER
RUN mkdir -p /var/www/html/var /var/www/html/public/media
VOLUME /var/www/html/var
VOLUME /var/www/html/public/media
