#syntax=docker/dockerfile:1.4
FROM registry.gitlab.com/dedyms/php-fpm:alpine AS builder
USER root
RUN apk add git nodejs npm && npm install -g yarn
WORKDIR /home/$CONTAINERUSER
USER $CONTAINERUSER
RUN git clone https://github.com/bierdok/pixapop.git pixapop
WORKDIR /home/$CONTAINERUSER/pixapop

USER $CONTAINERUSER
RUN wget https://getcomposer.org/download/1.10.22/composer.phar && \
    chmod +x ./composer.phar && \
    mv ./composer.phar ./composer && \
    ./composer global require hirak/prestissimo && \
    ./composer update && \
    ./composer install --prefer-dist --no-interaction && \
    ./composer clear-cache && \
    yarn install && \
    yarn build && \
    rm ./composer
