variables:
  CI_DOCKERHUB_REGISTRY_IMAGE: "martadinata666/jellyfin"
  DEV: ""
  TYPE: ""
  npm_config_cache: "$CI_PROJECT_DIR/.npm-cache"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"

stages:
  - build-web
  - buildx-docker-image-git
  - other

create-web:
  image: 192.168.0.2:5050/dedyms/jellyfin:dev-web
  stage: build-web
  cache: 
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store/
      - .npm-cache/
      - .yarn-cache/
    policy: pull-push
  before_script:
    #- pnpm config set store-dir .pnpm-store
    - git clone --depth=1 https://github.com/jellyfin/jellyfin-web.git jellyfin-web
  script:
    - cd jellyfin-web
    - npm -d -timeout=9999999 ci --no-audit --unsafe-perm
    - ls -alh ./
  after_script:
    - docker buildx stop
    - docker buildx rm
  artifacts:
    paths:
      - jellyfin-web/dist
  only:
    #refs:
    #  - master
    variables:
      - $DEV == "git"
    #changes:
    #  - .gitlab-ci.yml


buildx-git:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: buildx-docker-image-git
  #services:
  #  - docker:dind
  before_script:
    - export RELEASE="git"
    - export DATE=$(date +%Y%m%d)
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/amd64  -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$RELEASE" -t "$CI_REGISTRY_IMAGE:$DATE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$RELEASE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$DATE" . -f Dockerfile.sid
  after_script:
    - docker buildx stop
    - docker buildx rm
  only:
    refs:
      - master
    changes:
      - Dockerfile.sid
    variables:
      - $DEV == "git"


buildx-dev-dotnet:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: other
  #services:
  #  - docker:dind
  before_script:
    - export RELEASE="dev-dotnet"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/amd64 -t "$CI_REGISTRY_IMAGE:$RELEASE" . -f Dockerfile.dev-dotnet
  after_script:
    - docker buildx stop
    - docker buildx rm
  only:
    refs:
      - master
    changes:
      - Dockerfile.dev-dotnet
    variables:
      - $DEV == "dev-dotnet" || $DEV == "dev-both"

buildx-dev-web:
  # Official docker image.
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: other
  #services:
  #  - docker:dind
  before_script:
    - export RELEASE="dev-web"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/amd64 -t "$CI_REGISTRY_IMAGE:$RELEASE" . -f Dockerfile.dev-web
  after_script:
    - docker buildx stop
    - docker buildx rm
  only:
    refs:
      - master
    changes:
      - Dockerfile.dev-web
    variables:
      - $DEV == "dev-web" || $DEV == "dev-both"
