
FROM 192.168.0.2:5050/dedyms/node:lts-dev as web-builder
ARG JELLYFIN_WEB_VERSION=master
#RUN apk add --no-cache curl git zlib zlib-dev autoconf g++ make \
#     libpng-dev gifsicle alpine-sdk automake libtool make gcc musl-dev nasm python3 \
RUN apt update && apt install --no-install-recommends -y \
                      libpng-dev \
                      zlib1g-dev \
                      gifsicle \
                      python3-minimal \
                      python-is-python3 
