#curl -X POST -H "Content-Type: application/json" --data '{ "query": "{ metadataGenerate ( input : { sprites: true previews: false markers:false transcodes:false } ) }" }' localhost:9998/graphql

jobs:
  - name: scan files
    command: /supervisor/autoscan.sh
    shell: /bin/bash
    schedule: "0 */1 * * *"
    # auto rescan every 6 hours
  - name: generate things
    command: /supervisor/autogenerate.sh
    shell: /bin/bash
    schedule: "0 */3 * * *"
    # generate thumbnails, etct

logging:
  # In the format of:
  # https://docs.python.org/3/library/logging.config.html#dictionary-schema-details
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s %(levelname)s [%(name)s]: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers:
      - console
