web:
  listen:
     - http://127.0.0.1:8080
     - unix:///tmp/yacron.sock

defaults:
  shell: /bin/bash

jobs:
  - name: test-01
    command: echo "hello"
    schedule: "15 9 * * *"
    captureStdout: true
    utc: false
    timezone: America/Los_Angeles
    # timezone: UTC
