#FROM node:12.18.3-buster
FROM 192.168.0.2:5050/dedyms/node:lts-dev as builder

RUN sudo apt update -y && \
    sudo apt install wget curl net-tools python3 -y --no-install-recommends && \
    sudo npm -g install node-gyp
RUN mkdir -p shinobi/plugins
COPY --chown=$CONTAINERUSER:$CONTAINERUSER 4.1.0 shinobi/plugins/tensorflow
RUN wget https://gitlab.com/Shinobi-Systems/Shinobi/-/raw/dev/plugins/pluginBase.js -O $HOME/shinobi/plugins/tensorflow/pluginBase.js
RUN wget https://gitlab.com/Shinobi-Systems/Shinobi/-/raw/dev/tools/modifyConfigurationForPlugin.js -O $HOME/shinobi/plugins/tensorflow/modifyConfigurationForPlugin.js
RUN wget https://gitlab.com/Shinobi-Systems/Shinobi/-/raw/dev/plugins/pluginCheck.js -O $HOME/shinobi/plugins/pluginCheck.js
WORKDIR $HOME/shinobi/plugins/tensorflow
RUN npm -d --unsafe-perm --force install
#RUN npm -d rebuild @tensorflow/tfjs-node@2.7.0 build-addon-from-source


FROM 192.168.0.2:5050/dedyms/node:lts
ENV TFJS_HW=cpu \
    TF_ENABLE_ONEDNN_OPTS=1 \
    PLUGIN_NAME=Tensorflow \
    PLUGIN_HOST=localhost \
    PLUGIN_PORT=8080 \
    PLUGIN_HOST_PORT=8082 \
    PLUGIN_KEY=RANDOM \
    PLUGIN_MODE=client \
    PM2_HOME=/shinobi/tensorflow/pm2

RUN sudo npm -g install pm2
COPY --from=builder --chown=$CONTAINERUSER:$CONTAINERUSER $HOME/shinobi /shinobi
WORKDIR /shinobi/plugins/tensorflow
RUN sudo mkdir -p /config && sudo chown $CONTAINERUSER:$CONTAINERUSER /config
EXPOSE 8082
USER $CONTAINERUSER
ENTRYPOINT ["/shinobi/plugins/tensorflow/init.sh"]
CMD ["pm2-docker", "pm2.yml"]
