FROM golang:1.20-bullseye
RUN apt-get update && apt-get install -y --no-install-recommends \
    libtagc0-dev upx-ucl libicu-dev git ssl-cert make && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*