FROM 192.168.0.2:6060/dedyms/ffmpeg:8
RUN curl -fsSL https://deb.nodesource.com/setup_24.x | sudo bash - && \
    sudo apt-get install -y --no-install-recommends nodejs && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo npm --cache /dev/shm install -g npm && \
    sudo npm --cache /dev/shm install -g yarn && \
    sudo npm --cache /dev/shm install -g pnpm && \
    sudo rm -rf $HOME/.config && rm -rf $HOME/.npm
USER $CONTAINERUSER
CMD ["bash"]
