[unix_http_server]
file=/home/debian/supervisor/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/home/debian/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/home/debian/supervisor/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
#childlogdir=/home/debian            ; ('AUTO' child log dir, default $TEMP)
nodaemon=true

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///home/debian/supervisor/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

#[include]
#files = /etc/supervisor/conf.d/*.conf

[program:httpd]
command=apache2ctl -DFOREGROUND
user=debian
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-fpm]
command=php-fpm --nodaemonize
user=debian
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:notify-push]
command=/usr/local/bin/notify-push /var/www/html/config/config.php
user=debian
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[eventlistener:nextcloud-background]
command=python3 /usr/local/bin/event.py php -f /var/www/html/cron.php
user=debian
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
events=TICK_3600
;autorestart=true
;startsecs=300
