FROM 192.168.0.2:5050/dedyms/node:lts-dev AS tukang
ARG VERSION
ARG FRONTEND
RUN apt update && \
    apt install -y --no-install-recommends python3-pip python3-setuptools grc git python3-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
