
FROM 192.168.0.2:5050/dedyms/debian:dev
RUN apt update && \
    apt install -y --no-install-recommends redis libsass-dev libffi-dev libssl-dev openssh-client && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*