variables:
  GIT_STRATEGY: clone # clone entire repo instead of reusing workspace
  GIT_DEPTH: 1
  CI_DOCKERHUB_REGISTRY_IMAGE: "martadinata666/ffmpeg"

stages:
  - build
  - trigger

buildx-ffmpeg:
  image: 192.168.0.2:5050/dedyms/docker-with-buildx:latest
  stage: build
  before_script:
    - export DATE=$(date +%Y%m%d)
    - export NEO_RELEASE=$(grep -m1 "NEO_VERSION" 7/Dockerfile | cut -c17-)
    - echo $NEO_RELEASE
    - export FFMPEG_RELEASE=$(grep -m1 "FFMPEG_VERSION" 7/Dockerfile | cut -c21-)
    - echo $FFMPEG_RELEASE
    - export SHORT_FFMPEG_RELEASE=$(grep -m1 "FFMPEG_VERSION" 7/Dockerfile | cut -c21)
    - echo $SHORT_FFMPEG_RELEASE
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$CI_DOCKERHUB_REGISTRY_USER" -p "$CI_DOCKERHUB_REGISTRY_PASSWORD" $CI_DOCKERHUB_REGISTRY
#    - docker run --rm --privileged 192.168.0.2:5050/dedyms/docker-binfmt-qemu:sid
  script:
    - docker buildx create --use --config buildx-config.toml --driver-opt image=moby/buildkit:"$BUILDKIT_VERSION"
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/amd64
      -t "$CI_REGISTRY_IMAGE:$SHORT_FFMPEG_RELEASE"
      -t "$CI_REGISTRY_IMAGE:$FFMPEG_RELEASE-$NEO_RELEASE" . -f 7/Dockerfile
#    - docker buildx build --push --platform linux/amd64
#      -t "$CI_REGISTRY_IMAGE:$SHORT_FFMPEG_RELEASE"
#      -t "$CI_REGISTRY_IMAGE:$FFMPEG_RELEASE-$NEO_RELEASE"
#      -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$SHORT_FFMPEG_RELEASE" 
#      -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$FFMPEG_RELEASE-$NEO_RELEASE" . -f $TARGET/Dockerfile
  after_script:
    - docker buildx stop
    - docker buildx rm
  only:
    changes:
      - triggers
#      - 4/Dockerfile
#      - 5/Dockerfile
#      - 7/Dockerfile
#      - 6/Dockerfile
#  parallel:
#    matrix:
#      - TARGET: [7]

trigger-other-projects:
  image: 192.168.0.2:5050/dedyms/debian:latest
  needs: ["buildx-ffmpeg"]
  stage: trigger
  script:
    - curl -X POST --fail
      -F token=$NODE_TOKEN
      -F ref=master
      https://gitlab.ddyms.my.id/api/v4/projects/3/trigger/pipeline
    - curl -X POST
      -F token=$JELLYFIN_TOKEN
      -F ref=master
      -F "variables[TYPE]=stable"
      https://gitlab.ddyms.my.id/api/v4/projects/33/trigger/pipeline
  only:
    changes:
      - triggers
